### PR TITLE
python 3 compatible

### PR DESCRIPTION
**Pull request by PanarinM**
Made the code compatible with python 3.6, + some pep8 changes

### CODE REVIEW

**Comment by 4x1md** [comment]
Thanks for the request. I'll review it later this or next week.

**Comment by PanarinM** [comment]
@4x1md poke ;)

**Comment by 4x1md** [comment]
Sorry for the delay. I looked at your code and tested it with my DMM. The code works, but I have some questions.
1. Why do we need to import ```print_function``` in ```ut61e.py```? This module by definition does not print anything.
2. ```ut61e.py``` line 289. Why do we need the ```decode()``` function if we work with raw bytes and not with Unicode.

**Comment by PanarinM** [comment]
@4x1md 
1. My mistake, leftover from tests. Fixed
2. ord() takes can only take Unicode. Actually, we could skip the ord part entirely in python3. But in order to make it compatible with both versions i had to keep it that way

**Comment by 4x1md** [comment]
Merged. Thanks!

**Pull request merged**
